if (!require("cowplot")) install.packages("cowplot", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("brms")) install.packages("brms", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("BayesFactor")) install.packages("BayesFactor", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("tidyverse")) install.packages("tidyverse", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("lmerTest")) install.packages("lmerTest", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("MASS")) install.packages("MASS", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("lme4")) install.packages("lme4", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("lsmeans")) install.packages("lsmeans", repos = "https://cran.rstudio.com", dependencies = TRUE)
install.packages("https://cran.r-project.org/src/contrib/Archive/lsmeans/lsmeans_2.27-62.tar.gz", repos = NULL, dependencies = TRUE)
if (!require("kableExtra")) install.packages("kableExtra", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("caret")) install.packages("caret", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("NHANES")) install.packages("NHANES", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("pwr")) install.packages("pwr", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("ggplot2")) install.packages("ggplot2", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("emmeans")) install.packages("emmeans", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("tidyr")) install.packages("tidyr", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("fivethirtyeight")) install.packages("fivethirtyeight", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("ggfortify")) install.packages("ggfortify", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("knitr")) install.packages("knitr", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("boot")) install.packages("boot", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("gmodels")) install.packages("gmodels", repos = "https://cran.rstudio.com", dependencies = TRUE)
if (!require("sfsmisc")) install.packages("sfsmisc", repos = "https://cran.rstudio.com", dependencies = TRUE)
install.packages("https://cran.r-project.org/src/contrib/Archive/estimability/estimability_1.4.1.tar.gz", repos = NULL, dependencies = TRUE)
install.packages("https://cran.r-project.org/src/contrib/Archive/BayesMed/BayesMed_1.0.1.tar.gz", repos = NULL, dependencies = TRUE)
if (!require("bookdown")) install.packages("bookdown", repos = "https://cran.rstudio.com", dependencies = TRUE)
install.packages("https://cran.r-project.org/src/contrib/Archive/fiftystater/fiftystater_1.0.1.tar.gz", repos = NULL, dependencies = TRUE)
